### ISSUE TITLE
Tests fail in yesod-sqlite due to changes in new version of sqlite3

### ISSUE THREAD

**Issue by frt** [yesodweb/yesod-scaffold#155] opened 2017-07-18 14:32 UTC
Looks like the behavior of `PRAGMA foreign_keys=OFF` have changed after **sqlite-3.9**, I am having [this issue](https://stackoverflow.com/q/43169704/7941330) using **sqlite-3.11.0**.

**Comment by paul-rouse** [comment] 2017-07-18 16:48
The problem is not the `sqlite3` version, but rather the version of `persistent-sqlite` - version 2.6.2 enforced foreign key checks and broke `wipeDB` in the tests.  The tests as distributed don't populate the tables with any foreign keys, so this bug is not apparent immediately after creating a new scaffolding.  However, simply creating an entry in the email table whenever a user is created is sufficient to reproduce the issue.

What happens is this.  `wipeDB` uses a low-level "raw" connection to set `PRAGMA foreign_keys = OFF` and then wraps that same connection into a form suitable for persistent, using `wrapConnection`, in the hope that the foreign_keys setting still applies.  Unfortunately, `wrapConnection` sets its own idea of how foreign keys should be handled, which is ON.

Instead, in `persistent-sqlite>=2.6.2` you need to use `wrapConnectionInfo` with an `SqliteConnectionInfo` which sets the foreign keys checking OFF.

For a new scaffolded site, you can change the code to something like:
```
import Database.Persist.Sqlite (wrapConnectionInfo, mkSqliteConnectionInfo, fkEnabled)
import Lens.Micro              (set)
...
wipeDB app = do
    ...
    let infoNoFK = set fkEnabled False $ mkSqliteConnectionInfo ""
        wrapper = wrapConnectionInfo infoNoFK sqliteConn
    pool <- runLoggingT (createSqlPool wrapper 1) logFunc
```
I'll do a PR, but it looks as if it will be a bit of a conditional-compilation mess, since we need to support earlier versions of persistent as well.

**Comment by paul-rouse** [comment] 2017-07-18 18:10
Actually, do we need to support earlier versions?  What's the policy for the scaffolding @snoyberg ?

**Comment by snoyberg** [comment] 2017-07-18 18:34
I'm fine with dropping support, as long as the latest LTS is supported.

**Comment by paul-rouse** [comment] 2017-07-19 07:38
OK - cleaned up code in PR #156, which requires persistent-sqlite >= 2.6.2

**Comment by MaxGabriel** [comment] 2017-10-29 03:35
Closing as this looks fixed

**Closed by MaxGabriel** 2017-10-29 03:35 UTC
